name = "n8n-intelligence-backend"
main = "src/index.ts"
compatibility_date = "2024-04-17"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE"
index_name = "autorag-n8n-autorag"

[[r2_buckets]]
binding = 'N8N_NODES'
bucket_name = 'n8n-nodes'
